name: 'Task Completed Checker'
description: 'An action that checks if all tasks are completed in the pull requests.'
author: 'kentaro-m (forked by kamphaus)'
runs:
  using: 'node16'
  main: 'dist/index.js'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  uncompleted-as-error:
    description: 'Whether to treat any uncompleted tasks as an error. If true, uncompleted tasks will be show the Task Completed Checker check as an error, pending otherwise.'
    required: false
    default: 'false'
  scan-comments:
    description: 'Whether to also scan comments (issue comments, reviews, review comments). If set to false (default), only the PR description will be scanned for task lists.'
    required: false
    default: 'false'
branding:
  icon: 'check-square'
  color: 'green'
