name: 'Task Completed Checker'
description: 'An action that checks if all tasks are completed in the pull requests.'
author: 'kentaro-m (forked by kamphaus)'
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs: 
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  missing-as-error:
    description: 'Whether to treat any missing tasks as an error. If true, pending tasks will be show the Task Completed Checker check as an error, pending otherwise.'
    required: false
    default: 'false'
branding:
  icon: 'check-square'
  color: 'green'
