name: 'PR Tasks Check'
on: 
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  task-check:
    runs-on: ubuntu-latest
    steps:
      - uses: jemmic/task-completed-checker-action@master
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"